apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  accesskey: "<AppDynamics Account Access key base64 encoded>"
  accountname: "<Controller account name - short name - base64 encoded>"
