# AD-Capital Approval Node
#
# The current image (appddemo/adcapital-tomcat:latest) of the Approval Node contains
# performance and security issues that have been resolved in the version V2 image lincharles/adcapital-tomcat:latest
# The V2 image appears to not have been instrumented with AppDynamics
#
# Update History
# V1 - appddemo/adcapital-tomcat:latest
# V2 - lincharles/adcapital-tomcat:latest
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval
  labels:
    app: approval
    name: approval
    keel.sh/policy: force
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approval
  strategy:
    type: Recreate
  template:
    metadata:
      name: approval
      labels:
        app: approval
    spec:
      containers:
      - name: approval
        image: kevinbappd/adcapital-tomcat:latest
        envFrom:
          - configMapRef:
              name: env-map
        imagePullPolicy: Always
        #image: appddemo/adcapital-tomcat:latest
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/appdynamics/rook.jar"
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: mysecret
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              key: accountname
              name: mysecret
        - name: ROLE
          value: approval
        - name: APPDYNAMICS_AGENT_NODE_NAME
          value: Approval-Service
        - name: APPD_ANALYTICS_MONITOR
          value: "true"
        - name: APPD_DOCKER_VISIBILITY
          value: "true"
        - name: MACHINE_AGENT_PROPERTIES
          value: "-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=true"
          # valueFrom:
          #   fieldRef:
          #     fieldPath: metadata.name
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: Approval-Services
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /hostroot
          name: hostroot
          readOnly: true
        - mountPath: /project
          name: project
        - mountPath: /appdynamics
          name: appdynamics
      restartPolicy: Always
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: appdynamics
      - name: project
      initContainers:
        - image: kevinbappd/adcapital-project
          name: provider
          volumeMounts:
          - mountPath: /project
            name: project
        - name: fetch-rookout
          image: odise/busybox-curl
          command: ["curl","-L","http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.rookout&a=rook&v=LATEST","-o","/appdynamics/rook.jar"]
          volumeMounts:
          - mountPath: /appdynamics
            name: appdynamics
status: {}
# Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: approval
  name: approval
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: approval
status:
  loadBalancer: {}
