# harness.io/skip-file-for-deploy
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  accesskey: "NmQyODRiOGYtM2Q1Ny00NjZjLTkwNjMtMjJiN2JkYzRiN2Zl"
  accountname: "Y3VzdG9tZXIx"